[theme]
primaryColor             = "#3C3489"
backgroundColor          = "#EEEDFE"
secondaryBackgroundColor = "#DDD9FD"
textColor                = "#1A1735"
font                     = "sans serif"

[server]
headless = true
